spring.application.name=my-portfolio-backend

# Limpiamos la URL dejando únicamente el protocolo, el host de Neon y la BD
spring.datasource.url=jdbc:postgresql://ep-summer-block-atmrqbej-pooler.c-9.us-east-1.aws.neon.tech/portfolio?sslmode=require

# Dejamos las credenciales separadas en sus respectivas propiedades de Spring
spring.datasource.username=neondb_owner
spring.datasource.password=npg_X7tGgaoJxIe3
spring.datasource.driver-class-name=org.postgresql.Driver

# Configuración de Hikari Pool
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.connection-timeout=2000


#cada vez que spring se inicie configure las tablas y agregue los valores por defecto
spring.sql.init.mode=always